{% set name = "desdeo" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8cdc3a5623b24ee292a359c5178c6858cfa10975a7b6c8e7d3276ff60dc1916e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - pip
    - python >=3.6
    - pytest-runner
  run:
    - python >=3.6
    - numpy
    - prompt_toolkit <2
    - scikit-learn
    - scipy

test:
  imports:
    - desdeo
    - desdeo.core
    - desdeo.method
    - desdeo.optimization
    - desdeo.preference
    - desdeo.problem
    - desdeo.result
    - desdeo.utils

about:
  home: https://github.com/industrial-optimization-group/DESDEO
  license: MPL-2.0
  license_file: LICENSE
  summary: Open source library for for interactive multiobjective optimization
  description: |
    DESDEO is a free and open source Python-based framework for developing and
    experimenting with interactive multiobjective optimization. It includes the
    NIMBUS and NAUTILUS methods for finding Petero optimal solutions according
    to a descion maker's preferences.
  doc_url: https://desdeo.readthedocs.io/
  dev_url: https://github.com/industrial-optimization-group/DESDEO

extra:
  recipe-maintainers:
    - frankier
