{% set name = "desdeo" %}
{% set version = "0.2.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "5bbe8c7d9ccb82e9faf7ba6f66d82674171eab482b3eff795aacae9d214ec22d" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip
    - python >=3.6
    - pytest-runner
  run:
    - python >=3.6
    - numpy
    - prompt_toolkit <2
    - scikit-learn
    - scipy

test:
  imports:
    - desdeo
    - desdeo.core
    - desdeo.method
    - desdeo.optimization
    - desdeo.preference
    - desdeo.problem
    - desdeo.result
    - desdeo.utils

about:
  home: https://github.com/industrial-optimization-group/DESDEO
  license: MPL-2.0
  license_file: 'LICENSE'
  summary: Open source library for for interactive multiobjective optimization
  description: |
    DESDEO is a free and open source Python-based framework for developing and
    experimenting with interactive multiobjective optimization. It includes the
    NIMBUS and NAUTILUS methods for finding Petero optimal solutions according
    to a descion maker's preferences.
  doc_url: 'https://desdeo.readthedocs.io/'
  dev_url: 'https://github.com/industrial-optimization-group/DESDEO'

extra:
  recipe-maintainers:
    - frankier
