travis:
  secure:
    BINSTAR_TOKEN: coBUctVMjWWWOmMZ+5tgXn0Ca4da1PsS9mBaJ9ZyBPC6KIe3gjPSezRc2uDcSi/0zyM0Ec9mAZR+rLyID0erunHxhDl262VivAEVKLjs+2k4JlLPEyarpsO6HEIwXW56uzbknv6In5biTkmUJ4SHbOglS+Q9KW49tdPx4ObsDDZRaw84ZoQR8TNgD54saKqSGoCE6fsu4/2L3tBAeCe48c3XqqVXMoLFfI/Ibudxw1vOgG679EQgeIQDUKMCCwdARv2TyvjXKEgg+Qedm2vxdOFIW5NWdSAwqv/3XuQGF+KCIDfoz/6LXCOhJ+gOnBjN97DIH6KMNCi0Rk/7UhsDzPTOR1ujUpspd7BSIAM9mwZlXNP0FTIuaH8OYwRCUmHTZcztFBK/WVPBIcwjsaBETeiDoYCZwflUNYwK/gRs48c3GltukyKLaTObWJ6ebYPszPtn/RJ+7ifWX38Bj8wF0m67t/62lPEUlvEa4zBQLSdCyaY6+o2tYIbeXSKBWKdrsHBhfJfmMpHSXkGion+eqat80nc49RRJNV2G0MfbC9JkYN137fLB+8L9m7j+u7NlVt9Hu07WUiSVzhSHtUWPTOoupFCuyZSWOnQLbswFttZGNkDpNJM+KvLeD6rI1AVvgd2sC4Js+XBcyGVfPqFBB6ew22JI0I1yVKfVyQlaIrs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
