travis:
  secure:
    BINSTAR_TOKEN: sR3QRmLLS/rsaQlt5Pgirz0e4QX9gS2YdYeJXuozQagjYyBvGiUoF63vaw+VNvlN7XhoBxx4kV8Mk8yvxq4VwxRYduJXsQV3qRSUhDjVoE+XSyoHfMYMpNwJOLSQP+OCRBehD1h3w/FoaPqY2mxdxv5WLoRMdY/2GZ7amwpFmi72T3Dga5NgOI1UQR1TnXG02dcoRhf35jtZZkutR+CHm+Ag9Siace28mzesuMPgQOJVkBc+lbaGeNasqq7pnowzFesqP+0lprTW9i0OzklwdPlvbZwvUi5S/vTdfAd3IttIOYn8Y8ly98xxI8aeQgb+6Cq6BEwBHyd+0RIcEWk9dPy66LooAezP6aUcrfAb4PuVbg2KbayZNjgOPfM/4l4KYuM9Rc59s3r19lnTOsdJH3Vq2Cco0hOnjsqmTCr+r8xkYVpZTjJVa6ziZgh7AuHN4dp1YbVgjGp8oc+SD3GcBVthSVG39ZlebK8YswqEy01gcJTHGJD4HQm3ObaIvtFRraVOHr/KN5EFuz9b0LP4icDcIXHwR1aLEdoxfLwSgtlUfrCDuregUFiQH6J/cOrMHEuHLpWtMQ3lnEaGby6h3A0dtolLaPOyEq1ptv7YM/buz5gNMTBs+/dU+gZF1iow4bIwduXdabYJlj+COxNUWSFVsm63AbPHDF+nydvutH8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
